### ISSUE TITLE
code missing

### ISSUE THREAD

**Issue by youngstudent2** [CGCL-codes/naturalcc#4]
Dear author, 
when i try to train codenn on csn_feng for java,  running 
```shell script
CUDA_VISIBLE_DEVICES=0 python -m run.summarization.codenn.train -f config/csn_feng/java
```
I am getting this strange error:
```
Traceback (most recent call last):
  File "/home/youngstudent2/miniconda3/envs/ncc/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/youngstudent2/miniconda3/envs/ncc/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/d/github/DeepSoftwareAnalytics/naturalcc/run/summarization/codenn/train.py", line 16, in <module>
    from ncc import tasks
  File "/mnt/d/github/DeepSoftwareAnalytics/naturalcc/ncc/tasks/__init__.py", line 70, in <module>
    importlib.import_module('ncc.tasks.' + task_name)
  File "/home/youngstudent2/miniconda3/envs/ncc/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/mnt/d/github/DeepSoftwareAnalytics/naturalcc/ncc/tasks/type_prediction/__init__.py", line 1, in <module>
    from .type_prediction import TypePredictionTask
  File "/mnt/d/github/DeepSoftwareAnalytics/naturalcc/ncc/tasks/type_prediction/type_prediction.py", line 15, in <module>
    from ncc.data.type_prediction.codetype_dataset import CodeTypeDataset
  File "/mnt/d/github/DeepSoftwareAnalytics/naturalcc/ncc/data/type_prediction/codetype_dataset.py", line 10, in <module>
    from dataset.augmented_javascript.utils.util import normalize_program
ModuleNotFoundError: No module named 'dataset.augmented_javascript'
```

when i check the dataset folder, there isn't augmented_javascript, so is there something wrong? i have followed the readme in dataset/codesearchnet_feng to download
Thanks!

**Comment by whatsmyname** [comment]
Yes, we have not released some codes yet.
Plz, remove code lines that might report ModuleNotFoundError. 
This problem will be addressed in our next update. That will not be too long.

**Comment by nashid** [comment]
@whatsmyname when this would be sorted?
