### ISSUE TITLE
code missing

### ISSUE THREAD

**Issue by WZY0209** [CGCL-codes/naturalcc#7]
Dear author,
I can't find this code in run。

run/translation/bleu?

**Comment by whatsmyname** [comment]
This directory is deprecated. 
Please remove the code line.

**Comment by WZY0209** [comment]
Hello, how to solve this problem?

I have finished step one，but step two failed（python -m dataset.codesearchnet.attributes_cast）.

(codebert) dell@ubuntu:~/桌面/naturalcc-master$ python -m dataset.codesearchnet.attributes_cast
[2022-05-09 15:50:00]    INFO >> Cast attributes(['code', 'code_tokens', 'docstring', 'docstring_tokens', 'func_name']) of ruby-train dataset (attributes_cast.py:47, flatten())
ls: 无法访问 '/data/ncc_data/codesearchnet/raw/ruby/train/*.jsonl.gz': 没有那个文件或目录
ls: 无法访问 '/data/ncc_data/codesearchnet/attributes/ruby/train/code/*.jsonl': 没有那个文件或目录
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/codebert/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/dell/anaconda3/envs/codebert/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/dell/桌面/naturalcc-master/dataset/codesearchnet/attributes_cast.py", line 112, in <module>
    merge_attr_files(flatten_dir=args.attributes_dir, lang=lang, mode=mode, attrs=args.attrs)
  File "/home/dell/桌面/naturalcc-master/dataset/codesearchnet/attributes_cast.py", line 76, in merge_attr_files
    assert len(attr_files) > 0, RuntimeError('Attribute({}) files do not exist.'.format(attr))
AssertionError: Attribute(code) files do not exist.

**Comment by whatsmyname** [comment]
You might access the wrong data path as mentioned in:
`ls: 无法访问 '/data/ncc_data/codesearchnet/raw/ruby/train/.jsonl.gz': 没有那个文件或目录`
It may be `/data/ncc_data/codesearchnet/raw/ruby/train.jsonl.gz`.
